### PR TITLE
Add docs, playable demo and a few fix/changes to the engine

### LINKED ISSUE #84: Destroying an inherited object causes a bit of havoc
Let's do this:
```
item.new('stuff');
stuff.new('stuff2')
...
stuff.destroy();
stuff2
```
And we get:
```
TypeError: Cannot read property 'traitIds' of undefined
    at linearize (...src/lib/world-object-proxy-builder.js:5:9)
    at target.traitIds.forEach.traitId (...src/lib/world-object-proxy-builder.js:8:5)
    at Array.forEach (native)
    at linearize (...src/lib/world-object-proxy-builder.js:5:19)
    at Handler.get (...src/lib/world-object-proxy-builder.js:65:21)
    at output (...src/lib/print.js:47:39)
    at print (...src/lib/print.js:105:5)
    at printHelper (...src/lib/print.js:110:10)
    at ProgrammerController.onEval (...src/controllers/programmer-controller.js:23:27)
    at PlayerController.onInput (...src/controllers/player-controller.js:24:40)
```

That's kind of an embarrassment, as even **all()** breaks with the same error afterwards. One workaround is to manually reset the traits of the all offending children nodes (e.g. `stuff2.traits = []`), but you might not know/remember which it/them (e.g. the parent's destruction might even have been done by somebody else).

I experimented with the following graceful handling for this degraded case:

- In *world-object-proxy-builder.js*:
```
function linearize(target, db, linearization = new C3(target)) {
  target.traitIds.forEach((traitId, index) => {
    const trait = db.findById(traitId);
    if (trait !== undefined) {
        linearization.add(target, trait);
        linearize(trait, db, linearization);
    } else {
        // Attempt at gracefully handle broken trait chain
        target.traitIds.splice(index, 1);
    }
  });
  return linearization.run();
}
```

- And similarly in *world-object-class-builder.js*;
```
function linearize(object, linearization = new C3(object)) {
  object.traits.forEach((trait, index) => {
    if (trait !== undefined) {
        linearization.add(object, trait);
        linearize(trait, linearization);
    } else {
        // Attempt at gracefully handle broken trait chain
        object.traits.splice(index, 1);
    }
  });
  return linearization.run();
}
```

Seems to work on my local copy, unless I've missed any edge case... Would that be an appropriate fix/workaround, or is there a better way to handle this case ?

(For the record, another idea for a brief moment was to check all objects for possible dependency and reject the .destroy() call in that case, but don't think it's performance-wise.)

### LINKED ISSUE #86: Some strange crash with chokidar watcher
Observed on my Windows box: `someObject.destroy()` sometimes (but neither systematically nor even frequently) causes an abrupt exit with an "uncaughtException" trapped in 'on-exit.js', due to an EPERM error. The stack trace doesn't tell much beyond that and doesn't tell which file/directory caused it, but after having added try/catch's around all fs stuff in *fs-db.js*, it was still occurring - It only stopped (so far as it seems at least) when I commented out the chokidar watcher. (Sure, that's a pretty mean workaround, lol.)

Tracked here for the record, in any case it would be observed by others, but no investigation required yet, the point is maybe moot:
- It might be due to my modified fork, where I played with the directory structure and may have caused some havoc there (though I think I got the issue even before that. Will have to try to reproduce...)
- Or it might be Windows-specific, so well... ;)

### PR DESCRIPTION
**Pull request by Omikhleia**
Greetings, 

I am suggesting my master branch tag 3.1-RC for a pull request.

Note that the version in *package.json* is still 3.0.0, I leave it upon you to decide whether it must be upgraded.

Reviews and/or comments are obviously accepted :)

Details of the changes follow hereafter.

Code has been checked with eslint, and via a few playtest sessions.

# Changes overview

- Partial change #52 : New set of documentation (though it could of course still be expanded). Note: I have the docs in a sub-directory (rather than on a wiki), as I personally find it more convenient to update whenever the code changes.
- Fix #84
- Change #85 (partial) : Support for singularizers ('the', 'any', 'a', 'an') and selection by ordinal number ('1.item', 'item.1', 'item 2'). Note: Globalizers (i.e. 'all') are **not** supported yet (basic support is here, but eventually resulting in 'ambiguous' as before for multiple match), as this would likely require changes in the verb execution logic, but also changes in verb qualifiers,  and therefore changes to the client. I refrained from making such changes, since the current system as proposed is minimally ok for disambiguating objects with identical matches, and improves playability without requiring client editor changes.
- Fix #86 
- Change #87 (partial) : Add onPlayerCommandFailed() system hook for in-game customization. Note: I am still unsure the rest of the ideas in #87 are really pertinent, so I opted for the minimalist approach.
- Change : Allow on-disk file storage to be organized in sub-directories, with '\_' as pseudo-logical separator in object identifiers. Note: tested on Linux, but without long / exhaustive testplay sessions. Mostly tested on Windows, henceforth. Not tests on MacOS or other systems. The feature is by no mean mandatory (i.e. not using '\_' in identifiers results in a flat on-disk structure as before) - except for player objects, which are placed in the 'players\_' hierarchy and hence in a 'players/' sub-directory). That's actually the only place (beside FS DB / Moo DB) where the engine uses this features. All other 'core' objects (such as 'system', 'ambiguous', etc.) have been left at the top-level).
- Besides the above-mentioned changes or fixes, it also comes with a small demonstration world and library, so that one may start experimenting with something.

# Change details

*README.md*
- Leveraged the README for issue #52

*doc/...*
- Programming guide
- Customization guide
- Demonstration memorandum

*demo/...*
- A whole new demonstration world, illustrating as many features as possible, notably including expanded in-game help, command delegation, basic NPC (sellers and a moving mouse), verbMissing seller rooms, extraMatchObjects, etc.

*package.json*
- Bump chokidar dependency to 1.6.0 for fix #86

*src/controllers/player-controller.js*
- Update *parser.js* dependency as per change #85
- Implement onPlayerCommandFailed() hook as per change #87

*src/controllers/user-controller.js*
- Ensure player objects to be created in "players/" as per change "Allow on-disk file storage to be organized in sub-directories".

*src/lib/context.js*
- Update *parser.js* dependency and expose the new noun parser, as per change #85

*src/lib/fs-db.js*
- Fix #86

*src/lib/idify.js*
- Allow '_' in identifiers,  as per change "Allow on-disk file storage to be organized in sub-directories".

*src/lib/moo-db.js*
-  Change "Allow on-disk file storage to be organized in sub-directories".  That's where almost of this change is, since that's the place where almost all path-related code was.

*src/lib/parse.js*
- Add noun determiner parser, as per change #85

*src/lib/world-object-class-builder.js*
- Fix #84
- Handle noun determiners, as per change #85
- Sanitize identifiers on new()

*src/lib/world-object-proxy-builder.js *
- Fix #84

### CODE REVIEW

**Comment by Omikhleia** [comment]
Fixed (and slightly expanded) the travis/coverage tests, now all passed (tag 3.1-RC2)

I am unsure how to handle the hound reports - they all are on the demo, which should either be excluded from them, or have different rules (everything is normal there, as far as I can tell) - but that's new to me, I have no clue how to do this.

**Comment by vitogit** [comment]
Great work @Omikhleia , I was trying to do something similar to this repo, but you and @doughsay did a much better job. 
I´m trying to make the demo work but seems like something is missing. Could you help me? I'm on a mac osx using chrome.

I think is related to the loading moodb  subfolders or something. This is my .env 
```PORT=8889
LOG_LEVEL=trace
MAINTENANCE_MODE=false
USER_DB_FILE=demo/users.json
WORLD_DIRECTORY=demo/world```

There are some warnings when loading things, like  ```[2016-08-30T19:15:15.606Z]  WARN: rjs-server/7643 on TopTiers-Mini-3: tried loading object from fsdb, but failed (directory=demo/world, objectId=areas)
    SyntaxError: Unexpected token u in JSON at position 0
        at Object.parse (native)
        at MooDB.loadObject (/Users/TopTierlabs/apps/mush/room.js/src/lib/moo-db.js:70:27)
        at ids.forEach.id (/Users/TopTierlabs/apps/mush/room.js/src/lib/moo-db.js:42:12)
        at Array.forEach (native)
        at MooDB.load (/Users/TopTierlabs/apps/mush/room.js/src/lib/moo-db.js:41:9)
        at new MooDB (/Users/TopTierlabs/apps/mush/room.js/src/lib/moo-db.js:21:10)
        at RoomJSServer.setupState (/Users/TopTierlabs/apps/mush/room.js/src/lib/room-js-server.js:22:15)
        at new RoomJSServer (/Users/TopTierlabs/apps/mush/room.js/src/lib/room-js-server.js:16:10)
        at Object.<anonymous> (/Users/TopTierlabs/apps/mush/room.js/src/index.js:9:16)
        at Module._compile (module.js:556:32)```

In the client I pointed to the localhost server, I created the user and player without problems, and entered in play mode,  but when I write 'say hello' it's return 'I didn't understand that': and the error is ```[2016-08-30T19:20:36.210Z]  WARN: rjs-server/7643 on TopTiers-Mini-3: error running hook (socketId=/#sh2wHOlxCnPRW8gqAAAA, user=a, player=players_a)
    TypeError: player.tell is not a function
        at Proxy.onPlayerCommandFailed (evalmachine.<anonymous>:21:10)
        at World.runScript (/Users/TopTierlabs/apps/mush/room.js/src/lib/world.js:86:59)
        at Proxy.fn (/Users/TopTierlabs/apps/mush/room.js/src/lib/deserializer.js:33:22)
        at Verb::system.onPlayerCommandFailed:1:32
        at ContextifyScript.Script.runInContext (vm.js:35:29)
        at Object.exports.runInContext (vm.js:67:17)
        at World.run (/Users/TopTierlabs/apps/mush/room.js/src/lib/world.js:82:15)
        at PlayerController.onRunVerb (/Users/TopTierlabs/apps/mush/room.js/src/controllers/player-controller.js:114:16)
        at PlayerController.runCommand (/Users/TopTierlabs/apps/mush/room.js/src/controllers/player-controller.js:73:16)
        at PlayerController.onInput (/Users/TopTierlabs/apps/mush/room.js/src/controllers/player-controller.js:28:12)
```

Also the tab key don´t work for mode cycling.

**Comment by Omikhleia** [comment]
@vitogit 
Hmm my bad then, I might indeed have trimmed two many / in path names or broken some regexp in the Moo DB: the "but failed (directory=demo/world, objectId=areas)" message in your logs is suspicious, that the object id name was apparently truncated in a wrong way, it should have been something such as 'areas_somearea_someplace'). I have mostly tested on Windows, which gave me bad time with backslashes in path names, and might have done a late change that broke path handling in Unixes...
Thanks for testing and reporting, I'll have access to my Linux box next week-end and will check this... The pull request was probably a bit early thus, apologies to @doughsay...

**Comment by vitogit** [comment]
@Omikhleia I tested on windows and found some problems
1)I had to delete the npm-shrinkwrap.json file because it was trying to install chokidar 1.4.3 instead of 1.6. The old version cause problems on windows with fsevents.
2)npm start don´t work because the script uses unix syntax for the folder structure, probably using join.path could be better for cross-platform 

3)I think I found the problem with the object loading.
if you check the db size in FsDb after loading, it will say 13 on Linux/mac, but around 78 in Windows.  But on linux/mac the tree structure is correct, you can check it with inspectTree. So it´s seems that on windows (for some reason) is listing every item in the db in the same branch(root), and not creating the tree structure. 
So the solution is to check why on windows is happening that, and fix to use the tree structure, and then change the load method on mooDb to load the tree structure recursively.  I will try to fix it, but don´t have enough time.

**Comment by vitogit** [comment]
@Omikhleia  Changing the load method in moo-db to
```
  load(dir = '') {
    const ids = this.fsdb.lsDirs(dir);
    ids.forEach(id => {
      const filepath = path.join(dir, id); 
      this.load(filepath)
      this.loadObject(filepath.replace(/[\/\\]/g, '_'));
    });
  }
```
fix the problem in my mac, and now is working fine. All objects are loading, there are some warning because is trying to load some folders that don´t have json, like demo/world/players, but that doesn't affect gameplay.

**Comment by Omikhleia** [comment]
Thanks for the testing and feedback, @vitogit. Regarding your points:
1) `npm shrinkwrap` willl have to be regenerated and checked on a clean install. Point noted.
2) Yes, I didn't focus on that (i.e. currently starting with a separate .bat which i've not committed). There are other items in *package.json* to address if we want to make it fully Win-compliant (e.g. the dev/null in the tests sections) eventually, but that may possibly wait.
3) The reason why Win and Unixes behave differently here is that mapFor() / mapForDir() in FS DB split paths at '/', which doesn't occur on Win (I overlooked, this at some point). But on the other hand, fixing that (along with your change above) requires MOO DB to indeed work recursively, which I don't find really satisfying - What MOO DB should actually need to start-up is only the list of ids for objects to load (which may remain "flat" in a way), not the whole tree (of possibly empty dir levels). I'll have an attempts at refactoring the code in that direction.

**Comment by Omikhleia** [comment]
Now running on both Linux and Windows without the changes made for one breaking the other, and all path names behaving identically ^^. Everything seems to be running ok.

Finally kept the recursive approach from @vitogit above.

File: src/lib/fs-db.js [hunk 1]
```diff
@@ -84,7 +97,7 @@ class FsDb {
 
   mapFor(filepath, create = true) {
     const getCallback = create ? this.createOrGetMap.bind(this) : this.getMap.bind(this);
-    const keys = this.toRelpath(path.dirname(filepath)).split('/').filter(x => x);
+    const keys = this.toRelpath(path.posix.dirname(filepath)).split('/').filter(x => x);
```
Comment (vitogit) [inline src/lib/fs-db.js]: Instead of using path.posix so many times, I think you could change the requiere to `requiere: const path = require('path').posix;` and just use path

File: src/lib/fs-db.js [hunk 2]
```diff
@@ -6,11 +6,18 @@ const chokidar = require('chokidar');
...
+//   operating system, the path module will assume that Windows-style paths are being used."
+// Therefore, to avoid inconsistent behaviors, we enforce working with POSIX paths at our
+// level.
+
 class FsDb {
   constructor(directory, logger) {
     EventEmitter.call(this);
 
-    this.directory = path.normalize(directory).replace(/\/$/, '');
+    this.directory = path.posix.normalize(directory).replace(/\/$/, '');
```
Comment (vitogit) [inline src/lib/fs-db.js]: Is the replace needed now that you use posix?

File: src/lib/moo-db.js [hunk 3]
```diff
@@ -39,7 +40,16 @@ class MooDB {
...
     ids.forEach(id => {
-      this.loadObject(id.replace(/[\/\\]/g, '_'));
+      const filepath = path.posix.join(dir, id);
+      // Recurse
+      this.load(filepath);
+
+      // Load object contents
+      // Not the most efficient way to check that the directory
+      // has content to load, but we only do that at start-up.
+      if (this.fsdb.lsFiles(filepath).length) {
```
Comment (vitogit) [inline src/lib/moo-db.js]: Maybe you can add a isEmpty(filepath) or hasContent(filepath) method to the fsdb.

File: src/lib/fs-db.js [hunk 4]
```diff
@@ -108,54 +121,54 @@ class FsDb {
...
+    const relpath = this.toRelpath(filepath.replace(/[\\]/g, '/'));
     this.logger.trace({ relpath }, 'added to filesystem');
     this.loadFile(filepath);
   }
 
   onFileChanged(filepath) {
     const relpath = this.toRelpath(filepath);
     this.logger.trace({ relpath }, 'changed in filesystem');
-    this.loadFile(filepath);
+    this.loadFile(filepath.replace(/[\\]/g, '/'));
```
Comment (vitogit) [inline src/lib/fs-db.js]: Instead of using the replace here, I think you could use on setupWatcher like this
`.on('change', path => this.onFileChanged(path.replace(/[\\]/g, '/')) )`
but I think is almost the same and not sure if it will work, I'm not testing on windows.

Comment (Omikhleia) [inline src/lib/fs-db.js]: Good point. It does work, and allows having all those path-related replace at the same place.

File: src/lib/fs-db.js (hunk 1 above)
Comment (Omikhleia) [inline src/lib/fs-db.js]: Sure. Point taken.

File: src/lib/fs-db.js (hunk 2 above)
Comment (Omikhleia) [inline src/lib/fs-db.js]: That regexp was already here in the original code. This said, 'path' still leaves a trailing separator, if any, at the end of the configured directory in .env - There's no harm removing it to ensure the base directory does have any trailing separator afterwards.

File: src/lib/moo-db.js (hunk 3 above)
Comment (Omikhleia) [inline src/lib/moo-db.js]: Indeed. Point taken.

**Comment by doughsay** [comment]
Hey, thanks for the contributions! I've cleared out the newly ignored hound comments for the demo world.  I'll investigate why the 5 remaining get complaints from Hound but not when run locally.  If I can't figure it out, I'm just going to disable Hound.  Seems more trouble than it's worth...

**Comment by doughsay** [comment]
Let's just try disabling the no-resolved rule for eslint to get hound to stop bothering us about it.

I think I will eventually just turn off hound, since I have no control over what version of eslint it's running under the hood.  Better to have full control over it and run it manually from within travis the same way we'd run it locally.

**Comment by doughsay** [comment]
Ok, well I've just disabled hound altogether cause I realized I was already running eslint inside travis.  So that will catch any linting errors; no need to also include hound.

**Comment by doughsay** [comment]
Rebase on my latest master branch to get the removal of hound.yml and re-rerun the checks.

**Comment by doughsay** [comment]
Thanks for the contributions!  I'm going to go ahead and merge this.  There are a few places I'd still like to clean things up, but that can come later.
